import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Fireworks } from "fireworks-js/dist/react";

const options = {
  rocketsPoint: 50, // bottom center
  speed: 1,
  acceleration: 1.05,
  friction: 0.95,
  gravity: 1.5,
  particles: 50,
  trace: 3,
  explosion: 5,
  autoresize: true,
  hue: { min: 0, max: 360 },
  delay: { min: 15, max: 30 },
  sound: { enable: true },
  // boundaries: {
  //   x: 50,
  //   y: 50,
  //   width: container.clientWidth,
  //   height: container.clientHeight,
  // },
  // sound.files: ["public/sounds/public_sounds_explosion0.mp3"],
  // sound.volume:{ max: 2 },
  mouse: { click: false, move: false, max: 3 },
  brightness: { min: 50, max: 80 },
  // brightness.decay:{ min: 0.015, max: 0.03 },
};

const style = {
  left: 0,
  top: 400,
  width: "100%",
  height: "50%",
  position: "fixed",
  background: "#000",
};

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Fireworks</title>
        <meta name="description" content="Generated by create fireworks" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Fireworks!</h1>

        <div className={styles.grid}>
          <Fireworks options={options} style={style} />
        </div>
      </main>
    </div>
  );
};
export default Home;
